name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true
      - name: Test with Maven
        run: mvn -Dtest="ProductControllerTest, ProductServiceTest"

      - name: Send file to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RASPI_HOST }}
          username: ${{ secrets.RASPI_USER }}
          password: ${{ secrets.RASPI_PASSWORD }}
          port: ${{ secrets.RASPI_SSH_PORT }}
          source: "/home/runner/work/SpringBoot-Study/SpringBoot-Study/target/spring-example-0.0.1-SNAPSHOT.jar"
          target: project

      - name: Deploy remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPI_HOST }}
          username: ${{ secrets.RASPI_USER }}
          password: ${{ secrets.RASPI_PASSWORD }}
          port: ${{ secrets.RASPI_SSH_PORT }}
          script_stop: true
          script: |
            cd project/github/workspace/target
            sh deploy.sh
